# Generated by Django 6.0 on 2025-12-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='due_date',
        ),
    ]
